"""empty message

Revision ID: a0f7000440a7
Revises: 00a4a5974e98
Create Date: 2021-03-30 11:42:44.919631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f7000440a7'
down_revision = '00a4a5974e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permissions', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'permissions')
    # ### end Alembic commands ###
